version: "3"

services: 
  frontend:
    container_name: frontend
    build: ./frontend
    expose: 
      - 3000
    # volumes: 
    #   - ./frontend:/frontend
    #   - frontend/node_modules
    # networks:
    #   - frontend

  backend:
    container_name: backend
    build: ./backend
    expose: 
      - 5000
    # volumes: 
    #   - ./backend:/backend
    #   - backend/node_modules
    # networks:
    #   - backend

  nginx:
    container_name: nginx
    image: staticfloat/nginx-certbot
    ports:
      - 443:443
    environment:
      CERTBOT_EMAIL: knot131-wr@hotmail.com
    volumes:
      - ./nginx/conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt:

# networks: 
#   frontend:
#   backend: